name: Trigger auto deployment for container-app-cjcy7cxym4kv2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-cjcy7cxym4kv2-AutoDeployTrigger-97c00d6b-11d6-4ef4-9a66-9c09af625112.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPCJCY7CXYM4KV2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPCJCY7CXYM4KV2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPCJCY7CXYM4KV2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: defaultacrcontainerregistry9756.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPCJCY7CXYM4KV2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPCJCY7CXYM4KV2_REGISTRY_PASSWORD }}
          containerAppName: container-app-cjcy7cxym4kv2
          resourceGroup: todonodejspgsqlgoogleauth879e9766
          imageToBuild: defaultacrcontainerregistry9756.azurecr.io/container-app-cjcy7cxym4kv2:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


